[project]
name = "ri3d"
version = "0.1.0"
description = "RI3D: Few-Shot Gaussian Splatting With Repair and Inpainting Diffusion Priors"
readme = "README.md"
requires-python = ">=3.10,<3.11"
license = { text = "MIT" }
authors = [
    { name = "Avinash Paliwal" },
]

[project.urls]
Homepage = "https://people.engr.tamu.edu/nimak/Papers/RI3D/index.html"
Repository = "https://github.com/avinashpaliwal/RI3D"
Paper = "https://arxiv.org/abs/2503.10860"
