name: "gaussian_object"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
use_timestamp: False
exp_root_dir: "output"
seed: 0
 
data_type: "loo-datamodule"
dataset_type: "loo-dataset"
data:
  batch_size: 1
  data_dir: ""
  eval_camera_distance: 6.
  resolution: 4
  prompt: "a photo of a xxy5syt00"
  sparse_num: 4
  bg_white: True
  length: 4000
  around_gt_steps: 4000
  refresh_interval: 200
system_type: "gaussian-object-system"
system:
  enable_inpainting: False
  model_name: "control_v11f1e_sd15_tile"
  exp_name: ""
  lora_name: "lora-step=1799.ckpt"
  lora_rank: 64
  add_diffusion_lora: True
  add_control_lora: True
  add_clip_lora: True
  scene_extent: 5.0
  around_gt_steps: 4000
  ctrl_steps: 4000
  refresh_interval: 200
  controlnet_num_samples: 1
  gaussian_opt_params:
    iterations: 4000
    position_lr_init: 0.00016
    position_lr_final: 0.0000016
    scaling_lr: 0.003
    opacity_lr: 0.05
    position_lr_max_steps: 4000
    min_num_splats: 4000
    max_num_splats: 7000000
    densify_grad_threshold: 0.00005
    prune_opacity_threshold: 0.02
    densification_interval: 100
    opacity_reset_interval: 1000
    densify_from_iter: 0
    densify_until_iter: 4000
    random_background: True
    mono_rate: 0.5

  loss:
    lambda_l1: 0.5
    lambda_l2: 0.5
    lambda_lpips: 2.0
    lambda_tv: 0.05

  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15

trainer:
  max_steps: 4000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  limit_val_batches: 0
  enable_progress_bar: true
  precision: 32